### ISSUE TITLE
Snikket Private XMPP Chat on Oracle Cloud Free Tier - Virtually Potato

### ISSUE THREAD

**Issue by utterances-bot** [vimwtf/site-comments#1]
# Snikket Private XMPP Chat on Oracle Cloud Free Tier - Virtually Potato

Notes on installing a Snikket XMPP chat instance alongside a Matrix instance on an Oracle Cloud free tier server

[https://www.virtuallypotato.com/snikket-private-xmpp-chat-on-oracle-cloud-free-tier/](https://www.virtuallypotato.com/snikket-private-xmpp-chat-on-oracle-cloud-free-tier/)

**Comment by phijazz** [comment]
Is there a non-docker way to intall and use a snikket server?

**Comment by vimwtf** [comment]
@phijazz I don't think so. The Snikket server consists of several components and services which need to be configured *just so*. Shipping the solution packaged for Docker makes it easier for users to deploy correctly on a wide variety of systems.
