### ISSUE TITLE
Fixing WSL2 connectivity when connected to a VPN with wsl-vpnkit - Virtually Potato

### ISSUE THREAD

**Issue by utterances-bot** [vimwtf/site-comments#10]
# Fixing WSL2 connectivity when connected to a VPN with wsl-vpnkit - Virtually Potato

I was pretty excited to get WSL2 and Docker working on my Windows 10 1909 laptop a few weeks ago, but I quickly encountered a problem: WSL2 had no network connectivity when connected to my work VPN.

[https://virtuallypotato.com/fixing-wsl2-connectivity-when-connected-to-a-vpn-with-wsl-vpnkit](https://virtuallypotato.com/fixing-wsl2-connectivity-when-connected-to-a-vpn-with-wsl-vpnkit)

**Comment by bldrvnlw** [comment]
Thanks John for giving this some publicity! I've been hunting for a solution to "no network in WSL2 with work VPN" for quite a while. This solution actually works for VPNs other than Cisco (which is mentioned in most of the WSL issues). In my case I have to contend with F5 Big-IP VPN.

**Comment by vimwtf** [comment]
@bldrvnlw awesome, I'm glad I could help you find a solution! I guess I didn't actually mention it in the post, but I'm using `wsl-vpnkit` to connect to a Palo Alto GlobalProtect VPN.
