### ISSUE TITLE
vRA8 Custom Provisioning: Part Three - Virtually Potato

### ISSUE THREAD

**Issue by utterances-bot** [vimwtf/site-comments#11]
# vRA8 Custom Provisioning: Part Three - Virtually Potato

Picking up after Part Two, I now have a pretty handy vRealize Orchestrator workflow to generate unique hostnames according to a defined naming standard. It even checks against the vSphere inventory to validate the uniqueness. Now I’m going to take it a step (or two, rather) further and extend those checks against Active Directory and DNS.

[https://virtuallypotato.com/vra8-custom-provisioning-part-three](https://virtuallypotato.com/vra8-custom-provisioning-part-three)

**Comment by powertim** [comment]
Hi John, thank you so much for all the resources and explanations here!
I used to build my own workflow for the same purpose in vRO 7, and was curious about your solution in vRO 8.

I'm just surprised for the DNS part when you say : *Unfortunately there isn’t a corresponding pre-installed plugin that will work as a DNS client.*
I used to work with ``System.resolveHostName(hostname)`` and it's available for vRO 8 and also working correctly.
**But maybe you found some good reason to skip using this method ?**

By the way, your entire workflow looks very elegant to me ! Congrats and thanks again for sharing this nice work !

**Comment by vimwtf** [comment]
Hi @powertim!

Thanks for reaching out, for the kind words! I really started writing this stuff down for my own benefit but I'm thrilled to know that my notes are helping others.

There is indeed a reason I didn't use the much-simpler `System.resolveHostName(hostname)` approach: .... I somehow overlooked that option when I was cobbling together the workflow, and thus made the "avoiding DNS conflicts" step much harder than it needed to be.  *Whoopsie!* 

**Thank you for letting me know!** I did some quick testing and that definitely seems to work just as well (if not better), and it was easy to drop in to my `check for DNS conflicts` task and eliminate the need for the homemade module:
```js
var domain = requestProperties.dnsDomain
if (conflict) {
    System.log("Existing conflict found, skipping DNS check...")
} else {
    if (System.resolveHostName(candidateVmName + "." + domain)) {
        conflict == true;
        errMsg = "Conflicting DNS record found!"
        System.warn(errMsg)
        throw(errMsg)
    } else {
        System.log("No DNS conflict for " + candidateVmName)
    }
}
```

I'll add a note about that to the post, but will also leave the details about importing a script with dependencies in case that information can help someone (like Future John!) with a similar need in the future.

Thanks again!
