### ISSUE TITLE
Joining VMs to Active Directory in site-specific OUs with vRA8 - Virtually Potato

### ISSUE THREAD

**Issue by utterances-bot** [vimwtf/site-comments#12]
# Joining VMs to Active Directory in site-specific OUs with vRA8 - Virtually Potato

Connecting a deployed Windows VM to an Active Directory domain is pretty easy; just apply an appropriately-configured customization spec and vCenter will take care of it for you. Of course, you’ll likely then need to move the newly-created computer object to the correct Organizational Unit so that it gets all the right policies and such.

[https://virtuallypotato.com/joining-vms-to-active-directory-in-site-specific-ous-with-vra8](https://virtuallypotato.com/joining-vms-to-active-directory-in-site-specific-ous-with-vra8)

**Comment by sabale222** [comment]
Hi John,
Thanks for nice document.
is this adJoin resource available in vRA 8.3?

**Comment by vimwtf** [comment]
Hi @sabale222,

vRA 8.3 [introduced the ability](https://blogs.vmware.com/management/2021/02/whats-new-with-vrealize-automation-8-3-technical-overview.html#:~:text=New%20Active%20Directory%20Cloud%20Template%20Properties) for individual deployments to override the project-defined AD properties; that lets you have a Cloud Template determine whether or not a deployed VM should be joined to AD as well as what OU it should be created in. So yes, everything described in this post should work just fine in 8.3.

Let me know if you've got specific questions or issues with getting it working and I'll do my best to help out!

Cheers,
John

**Comment by virtualex-itv** [comment]
great post.  towards the end you refer to looking at an extensibility action run to verify that the machine deployed and joined AD but nowhere else is there any mention of this?  Is this required?  I'm having issues where the customization spec is not joining to the domain.  Can you cover what is required to setup the extensibility action?

**Comment by virtualex-itv** [comment]
disregard - i had the wrong view selected...doh! lol

**Comment by vimwtf** [comment]
@virtualex-itv I'm glad you found it! Please let me know if this is something I could make clearer in the post.

**Comment by virtualex-itv** [comment]
im still having issues getting domain join to work.  it almost seems as if vra is just not reading in the customization spec.  If I manually deploy a vm from template and use the customization spec, it works at expected.  but when issued from vra, the deployment takes much longer to show the user prompt and it never joins the domain.

**Comment by virtualex-itv** [comment]
i finally managed to get it to work.  the issue was with the customizationSpec comparison. you had...
`customizationSpec: '${input.adJoin ? "vra-win-domain" : "vra-win-workgroup"}'`

what utlimately worked for me in vRA 8.5.1 was...
`customizationSpec: '${input.adJoin == true ? "vra-win-domain" : "vra-win-workgroup"}'`

**Comment by vimwtf** [comment]
Hey @virtualex-itv,

Sorry to leave you hanging on this - I managed to break my lab environment over the weekend trying to get [Tanzu Community Edition](https://tanzucommunityedition.io/) rolled out alongside the vRA setup so I wasn't able to double-check my configuration until this morning. But I'm glad to hear you managed to get it sorted on your own!

That's interesting that the `${input.adJoin ? "domain" : "workgroup"}` statement doesn't work in your case. I've just confirmed that that is the structure I'm using both in my lab as well as my production environments and it's working fine for me (across 8.4.1, 8.5, and 8.5.1). Since `adJoin` is defined in the `inputs:` section as a boolean, it _should_ automatically evaluate to `true` or `false` without needing to explicitly test for it. 

In any case, thanks for letting me know about the issue! I'll do some testing on my end to see if I can figure out what might be preventing it from working as-written on yours.

**Comment by virtualex-itv** [comment]
Hey @jbowdre - thanks for following up, it is strange indeed but I'm glad I got it working now.  Any chance you can do a similar write up of this but using `cloudbase-init` instead?  I've been searching around but I keep running into an error.  Your guide was easy to follow and right on the money.  Keep up the great content!

**Comment by vimwtf** [comment]
@virtualex-itv I played with `cloud-init` early on but ran into issues as well. Mine were self-imposed, though: my environment requires static IP addressing, and the way that vRA configures those (an extra guest customization spec inserted into the deployment process) interferes with `cloud-init`'s expected operation flow. 

I've not had a chance (or reason, really) to revisit that yet but I'll keep it in mind for further explorations. I would definitely like to learn more about the process even if I can't (currently) make use of it in prod.

**Comment by virtualex-itv** [comment]
@jbowdre - sounds good, I'm tinkering a bit with it now in hopes to get it working levering only cloudbase-init and no customizationSpec.  I'll keep you posted.

**Comment by bstreet1967** [comment]
This is a great article for deploying to OU's based on project.  How would you go about it if you have OU's based on blueprints instead? Our projects have 32 and 64bit blueprints that go into separate OU's.

**Comment by vimwtf** [comment]
@bstreet1967 If you've got separate blueprints ("Cloud Templates") for the different architectures you could just update the `relativeDN` property directly without needing to do all the extra work to make it flexible. Just set something like this in the template and be done with it:
```
[...]
resources:
  Cloud_vSphere_Machine_1:
    type: Cloud.vSphere.Machine
    properties:
      activeDirectory:
        relativeDN: "OU=x86,OU=Servers,OU=Computers,OU=LAB"'
[...]
```

I'd probably map it to the `image` being selected though and be able to use one Cloud Template for both architectures. Something like this should do the trick:
```
inputs:
  image:
    type: string
    title: Operating System
    oneOf:
      - title: Some OS (x86)
        const: someos-x86
      - title: Some OS (x64)
        const: someos-x64
[...]
resources:
  Cloud_vSphere_Machine_1:
    type: Cloud.vSphere.Machine
    properties:
      activeDirectory:
        relativeDN: '${"OU=" + substring(input.image,length(input.image) - 3, length(input.image)) + ",OU=Servers,OU=Computers,OU=LAB"}'
[...]
```

So then the machine would be placed in either `LAB\Computers\Servers\x86\` or `LAB\Computers\Servers\x64\` depending on which `image` was selected.
