### ISSUE TITLE
AdGuard Home in Docker on Photon OS - Virtually Potato

### ISSUE THREAD

**Issue by utterances-bot** [vimwtf/site-comments#13]
# AdGuard Home in Docker on Photon OS - Virtually Potato

I was recently introduced to AdGuard Home by way of its very slick Home Assistant Add-On. Compared to the relatively-complicated Pi-hole setup that I had implemented several months back, AdGuard Home was much simpler to deploy (particularly since I basically just had to click the “Install” button from the Home Assistant add-ons manage). It also has a more modern UI with options arranged more logically (to me, at least), and it just feels easier to use overall. It worked great for a time… until my Home Assistant instance crashed, taking down AdGuard Home (and my internet access) with it. Maybe bundling these services isn’t the best move.

[https://virtuallypotato.com/adguard-home-in-docker-on-photon-os](https://virtuallypotato.com/adguard-home-in-docker-on-photon-os)

**Comment by dharampaul** [comment]
Thanks John for a very detailed instructions. It worked as written in this tutorial. Thanks for your time.

**Comment by vimwtf** [comment]
@dharampaul you're welcome! I'm glad that you found it useful.
