### ISSUE TITLE
Creating static records in Microsoft DNS from vRealize Automation - Virtually Potato

### ISSUE THREAD

**Issue by utterances-bot** [vimwtf/site-comments#16]
# Creating static records in Microsoft DNS from vRealize Automation - Virtually Potato

One of the requirements for my vRA deployments is the ability to automatically create a static A records for non-domain-joined systems so that users can connect …

[https://www.virtuallypotato.com/creating-static-records-in-microsoft-dns-from-vrealize-automation/](https://www.virtuallypotato.com/creating-static-records-in-microsoft-dns-from-vrealize-automation/)

**Comment by vmwarelab** [comment]
Great blog. 

one thing I found is with the deleted a record java script 
you need to change the created ==false to deleted ==false since its not declared the workflow will be flagged as fail even though the record is deleted 
sshSession.disconnect()
    if (created == false) {
        System.warn("Error! Unable to delete DNS record.")

**Comment by vimwtf** [comment]
@vmwarelab thanks for spotting that! It looks like I had it correct in my lab environment but goofed when transcribing the code into the post. I'll get that corrected momentarily. 

Thanks again!

**Comment by huynhr6510** [comment]
we deploy Windows VM with dynamic DNS record assigned and the record is not removed when the deployment is deleted.  What would be the trick to delete a dynamic record?  Thanks

**Comment by vimwtf** [comment]
@huynhr6510 Hmm, that's an interesting question. I haven't looked into that. For my Windows VMs that self-register in DNS through Active Directory I just let the records get scavenged automatically a few days after the VMs are deleted.
