### ISSUE TITLE
Virtually Potato migrated to GitHub Pages! - Virtually Potato

### ISSUE THREAD

**Issue by utterances-bot** [vimwtf/site-comments#2]
# Virtually Potato migrated to GitHub Pages! - Virtually Potato

After a bit less than a year of hosting my little technical blog with Hashnode, I spent a few days migrating the content over to a new format hosted with GitHub Pages.

[https://virtuallypotato.com/virtually-potato-migrated-to-github-pages](https://virtuallypotato.com/virtually-potato-migrated-to-github-pages)

**Comment by vimwtf** [comment]
🥳🎉
