### ISSUE TITLE
Active Directory authentication in Tanzu Community Edition - Virtually Potato

### ISSUE THREAD

**Issue by utterances-bot** [vimwtf/site-comments#20]
# Active Directory authentication in Tanzu Community Edition - Virtually Potato

Deploying and configuring a Tanzu Community Edition Kubernetes cluster to support authentication with Active Directory users and groups by using pinniped and …

[https://www.virtuallypotato.com/ldaps-authentication-tanzu-community-edition/](https://www.virtuallypotato.com/ldaps-authentication-tanzu-community-edition/)

**Comment by bluebossa63** [comment]
Awesome write-up, you saved me a lot of work with this jump start!

**Comment by vimwtf** [comment]
@bluebossa63 Fantastic, that's great to hear that this helped you!
