### ISSUE TITLE
ESXi Arm Edition on the Quartz64 SBC - Virtually Potato

### ISSUE THREAD

**Issue by utterances-bot** [vimwtf/site-comments#22]
# ESXi Arm Edition on the Quartz64 SBC - Virtually Potato

Getting started with the experimental ESXi Arm Edition fling to run a VMware hypervisor on the PINE64 Quartz64 single-board computer, and installing a Tailscale …

[https://www.virtuallypotato.com/esxi-arm-on-quartz64/](https://www.virtuallypotato.com/esxi-arm-on-quartz64/)

**Comment by kuklis** [comment]
Is the onboard NIC still unsupported?

**Comment by vimwtf** [comment]
> Is the onboard NIC still unsupported?

Yes, as of the current releases (ESXi ARM Fling 1.9, quartz64_uefi 2022-04-16) the onboard NIC is still not working.

**Comment by vimwtf** [comment]
Great news, @kuklis! ESXi-Arm Fling 1.10 now supports the onboard NIC! :thumbsup:
