### ISSUE TITLE
Finding the most popular IPs in a log file - Virtually Potato

### ISSUE THREAD

**Issue by utterances-bot** [vimwtf/site-comments#3]
# Finding the most popular IPs in a log file - Virtually Potato

I found myself with a sudden need for parsing a Linux server’s logs to figure out which host(s) had been slamming it with an unexpected burst of traffic. Sure, there are proper log analysis tools out there which would undoubtedly make short work of this but none of those were installed on this hardened system. So this is what I came up with.

[https://virtuallypotato.com/finding-the-most-popular-ips-in-a-log-file](https://virtuallypotato.com/finding-the-most-popular-ips-in-a-log-file)

**Comment by vimwtf** [comment]
**Vamsi Rao**
*Posted September 15, 2020 on [Hashnode](https://hash.virtuallypotato.com/finding-the-most-popular-ips-in-a-log-file#ckf4a6h5a00vy6ws1chaeaxjf)*

This is super cool! I also have an article in my drafts on how we can do so many things using grep/zgrep, especially with server logs. Bookmarked :)

**Comment by vimwtf** [comment]
**John Bowdre**
*Posted September 15, 2020 on [Hashnode](https://hash.virtuallypotato.com/finding-the-most-popular-ips-in-a-log-file#ckf4agie700yj8cs14urc2mb5)*

Thanks! I'd definitely like to see what other tricks you can come up with for grep/zgrep.
