### ISSUE TITLE
Showdown: Lenovo Chromebook Duet vs. Google Pixel Slate - Virtually Potato

### ISSUE THREAD

**Issue by utterances-bot** [vimwtf/site-comments#4]
# Showdown: Lenovo Chromebook Duet vs. Google Pixel Slate - Virtually Potato

Okay, okay, this isn’t actually going to be a comparison review between the two wildly-mismatched-but-also-kind-of-similar Chromeblets, but rather a (hopefully) brief summary of my experience moving from an $800 Pixel Slate + $200 Google keyboard to a Lenovo Chromebook Duet I picked up on sale for just $200.

[https://virtuallypotato.com/showdown-lenovo-chromebook-duet-vs-google-pixel-slate](https://virtuallypotato.com/showdown-lenovo-chromebook-duet-vs-google-pixel-slate)

**Comment by vimwtf** [comment]
**Vivek Tiwari**
*Posted November 7, 2020 on [Hashnode](https://hash.virtuallypotato.com/showdown-lenovo-chromebook-duet-vs-google-pixel-slate#ckh7j892403pes9s190il498t)

Pixel slate looks damn beautiful. 😍

**Comment by vimwtf** [comment]
**John Bowdre**
*Posted November 7, 2020 on [Hashnode](https://hash.virtuallypotato.com/showdown-lenovo-chromebook-duet-vs-google-pixel-slate#ckh7savz504wmras125j7cgpt)

Oh for sure, the Pixel Slate is a lovely piece of hardware. The Duet isn't nearly as attractive.
