### ISSUE TITLE
vRA8 Custom Provisioning: Part Two - Virtually Potato

### ISSUE THREAD

**Issue by utterances-bot** [vimwtf/site-comments#6]
# vRA8 Custom Provisioning: Part Two - Virtually Potato

We last left off this series after I’d set up vRA, performed a test deployment off of a minimal cloud template, and then enhanced the simple template to use vRA tags to let the user specify where a VM should be provisioned. But these VMs have kind of dumb names; right now, they’re just getting named after the user who requests it + a random couple of digits, courtesy of a simple naming template defined on the project’s Provisioning page:

[https://virtuallypotato.com/vra8-custom-provisioning-part-two](https://virtuallypotato.com/vra8-custom-provisioning-part-two)

**Comment by vimwtf** [comment]
**Justin Chismar**
*Posted May 27, 2021 on [Hashnode](https://hash.virtuallypotato.com/vra8-custom-provisioning-part-two#ckp73qk1e08krvws1423j2k7c)*

Hey John, first and foremost...this is an AMAZING well documented step by step. Would you possibly be able to post screenshots of the "Variables" tab and the "Inputs/Outputs" tabs of all the main workflows so we can cross reference? Not sure if it would even be possible to do an export/import of your workflow to see where we screwed up. I am having a hard time wrapping my head around some of this (due to my lack of vRA experience, not your instructions) and think that these screenshots would be extremely helpful for beginners! :)

We are looking to do custom naming and are testing out your procedure. Was thinking we would never find a way to do all of this custom naming and checks to DNS/AD until we fumbled on this, so thank you very much for taking the time and energy to document this all, it's greatly appreciated!!

**Comment by vimwtf** [comment]
**John Bowdre**
*Posted May 27, 2021 on [Hashnode](https://hash.virtuallypotato.com/vra8-custom-provisioning-part-two#ckp790ljh0glamds164sjhkia)*

Justin,

Thanks for the kind words! I'm so glad that you found my write-up to be useful.

Do these screenshots help to identify what might be missing?

(right-click -> open in new tab to make them actually readable)

![image](https://user-images.githubusercontent.com/61015723/126701357-252af0c0-2974-4a38-9d60-5c449122cc95.png)

![image](https://user-images.githubusercontent.com/61015723/126701376-fd2e58eb-d628-4033-be26-ee5740180478.png)

![image](https://user-images.githubusercontent.com/61015723/126701389-182f688c-0593-4c15-a450-cc76a0b8d465.png)

![image](https://user-images.githubusercontent.com/61015723/126701425-48322be2-1c17-4529-b15a-20df63c33eea.png)

I also exported a package containing these workflows, which you should be able to import directly into vRO to review:
https://github.com/jbowdre/misc-scripts/blob/main/vRealize/net.bowdre.customNaming.package

Please do let me know how it goes!

Cheers, John

**Comment by vimwtf** [comment]
**Justin Chismar**
*Posted May 27, 2021 on [Hashnode](https://hash.virtuallypotato.com/vra8-custom-provisioning-part-two#ckp7ale3a09umvws15vtzauqd)*

That is perfect and will help out tremendously! I should be able to use these screenshots to compare and hopefully find out where I screwed up. I'll for sure come back and let you know how it worked. I owe you many beers for the assist!

Thanks, Justin

**Comment by vimwtf** [comment]
**Dennis**
*Posted June 30, 2021 on [Hashnode](https://hash.virtuallypotato.com/vra8-custom-provisioning-part-two#ckqkdmjsn08fza6s10r4cdv86)*

Hi John,

Slightly off-topic but I could not find a way to connect with you via PM: I have an enhancement request for your logPayloadProperties action for SaltStack Config.

This is above my ability but I'm hoping for you it would be easy...

Right now, SSC and vRA are separate products owned by VMware - yes there is minimal integration when it comes to the vRA Cloud Template (or blueprint) to help install minions, but the big issue for me is that there is no way that the Salt Master can consume any of the vRA deployment properties - i.e. property groups, input values, secrets, machine properties etc. You have to run a command on the target VM's minion to set a "grain" - basically a key/value pair that will be inserted into the Salt Master database for this minion. After this is done these grains are used for all the salt functions.

Luckily there is an easier way of defining the grains rather than setting each one individually via salt-call grans.set function. You can basically touch the /etc/salt/grains file directly and then restart the minion: https://docs.saltproject.io/en/latest/topics/grains/index.html

Here's an example of my grains file on a vRA-deployed machine after setting some grains individually using run-cmd:

appName: app1 hardened: true serverRole: webserver software-loginsight: true software-tmds: true

So, to the request....

Would it be possible to enhance the logPayloadProperties to extract the payload into the format of the grains file and then copy that file (using Invoke-VMScript perhaps?) to the deployed VM?

**Comment by vimwtf** [comment]
**John Bowdre**
*Posted July 1, 2021 on [Hashnode](https://hash.virtuallypotato.com/vra8-custom-provisioning-part-two#ckql1c0ds02ccd7s1avkg9tkn)*

Hi Dennis!

I played a bit with the SSC "integration" as well, and was similarly disappointed by the lack of real, well, integration between vRA and SSC. I got as far as implementing an ABX action to deploy the Salt minions (via `Invoke-VMScript`)... and then realized that I could just run the configuration changes I wanted directly that way without involving SSC at all. That of course doesn't address longer-term configuration management, but it took care of my immediate needs. (You can see a taste of what I've been working on in that area [here](https://github.com/jbowdre/misc-scripts/tree/main/vRealize), in case you're interested.)

All that is to say that I'm really not very familiar with Salt at all. I could probably adapt that logging action to do what you need given enough free time, but I'm afraid I'm running a bit low on that at the moment. (And I'm also waay behind on documenting the rest of my vRA project - see above!) I also don't have a working Salt environment to test if I got it correct anyway.

If I were to attempt this, though, I'd probably do it with an ABX script written in PowerShell, and leverage `ConvertFrom-Json` and `ConvertTo-Yaml` to easily convert the deployment properties passed in as JSON to the YAML format of a Grains file. Something like `$grains = ($inputs.customProperties | ConvertFrom-Json) | ConvertTo-Yaml` might get you pointed in the right direction.

Or my (limited) understanding of Salt could be way off. Either way, I'd love to see what you come up with if you manage to tackle this!

Feel free to hit me up [on Matrix](https://virtuallypotato.com/federated-matrix-server-synapse-on-oracle-clouds-free-tier) if you want to chat: [@john:bowdre.net](https://matrix.to/#/@john:bowdre.net)

Cheers, John

**Comment by bstreet1967** [comment]
Hi John, might have missed it but where do you actually change the name of the VM?

**Comment by vimwtf** [comment]
Hi @bstreet1967,

That happens in the `Apply new name` task in the [wrapper workflow](https://virtuallypotato.com/vra8-custom-provisioning-part-two#wrapper-workflow):

```
// JavaScript: Apply new names
//    Inputs: inputProperties (Properties), newNames (Array/string)
//    Outputs: resourceNames (Array/string)

resourceNames = inputProperties.get("resourceNames");
for (var i = 0; i < newNames.length; i++) {
    System.log("Replacing resourceName '" + resourceNames[i] + "' with '" + newNames[i] + "'");
    resourceNames[i] = newNames[i];
}
```

This is where it's taking the `newNames` array output from the nested workflow and inserting it into the `resourceNames` array which gets handed back to vRA.

I realize now that I didn't make that super clear in the post so thank you for bringing that to my attention! I'll see if I can edit the post to make it a bit more clear.

Cheers,
John

**Comment by bryanzxcxd** [comment]
Hi I've appeared to run into a problem at the end it says its changing resourcename with the resourcename generated but when it gets deployed the name is still the old resourcename did i set up something wrongly?
ps: just got into vra for school project so i might have done some obvious stuff wrongly

**Comment by vimwtf** [comment]
Hi @bryanzxcxd,

Does the log message correctly indicate both the original name and the one which was generated by the workflow?

**Comment by bryanzxcxd** [comment]
Yup its the same

**Comment by bryanzxcxd** [comment]
i did change the site name to public/private but i also updated the variable could that have been the problem? 
heres the system log
2022-01-26 18:16:27.613 +08:00INFO__item_stack:/item3/item4/item2
2022-01-26 18:16:27.639 +08:00INFO__item_stack:/item3/item4/item0
2022-01-26 18:16:27.658 +08:00INFO__item_stack:/item3/item4
2022-01-26 18:16:27.676 +08:00INFO__item_stack:/item3/item5
2022-01-26 18:16:27.689 +08:00INFO__item_stack:/item3/item6
2022-01-26 18:16:27.733 +08:00INFOProposed VM name: PUBLIC-DTST-432001
2022-01-26 18:16:27.743 +08:00INFO__item_stack:/item3/item7
2022-01-26 18:16:27.746 +08:00INFONo VM name conflicts found for PUBLIC-DTST-432001
2022-01-26 18:16:27.768 +08:00INFO__item_stack:/item3/item10
2022-01-26 18:16:27.772 +08:00INFO ***** Selecting [PUBLIC-DTST-432001] as the next VM name ***** 
2022-01-26 18:16:27.782 +08:00INFO__item_stack:/item3/item11
2022-01-26 18:16:27.803 +08:00INFO__item_stack:/item3/item9
2022-01-26 18:16:27.812 +08:00INFO__item_stack:/item3
2022-01-26 18:16:27.818 +08:00INFO__item_stack:/item4
2022-01-26 18:16:27.821 +08:00INFOReplacing resourceName 'Cloud_vSphere_Machine_1-mcm386-191585782597' with 'PUBLIC-DTST-432001'
2022-01-26 18:16:27.826 +08:00INFO__item_stack:/item0

**Comment by vimwtf** [comment]
@bryanzxcxd Can you confirm that you've got the `resourceNames` Array/string being returned as an Output of the "Apply new names" task, and also as an Output of the entire "VM Provisioning" wrapper workflow? I don't think I did a great job of spelling that out in the post.

**Comment by bryanzxcxd** [comment]
hi it works now i set resourceNames as a variable instead of an output thanks so much for your help i wouldn't have been able to finish my project without your blog

**Comment by vimwtf** [comment]
@bryanzxcxd Excellent, I'm glad to hear you got it sorted!

I definitely need to update this article to make that output clearer. (Of course *someone* blew up my lab vRA instance so I've got to rebuild it first - good thing I took notes!)

**Comment by huynhr6510** [comment]
Hi John,

I am having the same issue as  bryanzxcxd, the VM name did not change as expected.  I have confirmed the resourceNames Array/string being returned as an Output of the "Apply new names" task.  Would you please explain how to set the resourceNames as "as an Output of the entire "VM Provisioning" wrapper workflow"?  Much appreciated.  Thanks

**Comment by vimwtf** [comment]
Hi @huynhr6510,

Go to the **Inputs/Outputs** tab of the *VM Provisioning* wrapper workflow, click **New**, and create a new Output Parameter named `resourceNames` of type `Array/string`:
![image](https://user-images.githubusercontent.com/61015723/159510490-bea92af0-ab79-4c7d-b06f-453670fd05b0.png)

It should look like this:
![image](https://user-images.githubusercontent.com/61015723/159510701-a56bb765-8c4b-4e1f-9664-e8177597b6f0.png)

Now you need to map it to the result being returned by the *Apply new names* task. Do that by going to the **Schema**, selecting the *Apply new names* task, expanding the **Inputs/Outputs** section, and clicking where it says "Select variable" next to the `resourceNames` task output. From there, select the variable you created a moment ago.

![image](https://user-images.githubusercontent.com/61015723/159511415-c9739643-8358-4575-8acb-e2a6f9a7c117.png)

Hit the **Save** button to save the changes to the workflow, and then go back to the **Inputs/Outputs** tab and you can confirm that `resourceNames` is now referenced by the *Apply new names* task.

![Screenshot 2022-03-22 09 56 53](https://user-images.githubusercontent.com/61015723/159512121-e78d1441-b323-48f0-a20c-813702de75ed.png)

Subsequent deployments should get renamed appropriately. Please let me know how it goes - if these notes help to clarify the process a bit better I'll get them added to the post.

Cheers,
John

**Comment by huynhr6510** [comment]
yeah, it works.  It would be helpful to add those notes.  Very helpful article, enjoy it.  Thanks a bunch!

**Comment by vimwtf** [comment]
Thanks for the feedback @huynhr6510! I've updated the [Wrapper Workflow](https://www.virtuallypotato.com/vra8-custom-provisioning-part-two/#wrapper-workflow) section with specific notes on setting the output of the `Apply new names` task to be a Workflow Output. I hope that will help anyone who comes across this in the future.

Thanks again!

**Comment by sjm-tech** [comment]
Hi John, I have set this up for one of my clients on vRA 8.4. Everything works except for some reason the workflow is stuck at creating lock and does not proceed any further. I remember that it ran successfully the first time but we had cancelled the task within the vRA service catalog. For now I have removed the create lock and remove lock scripting tasks. Any Idea what could be the reason.

**Comment by vimwtf** [comment]
Hi @sjm-tech,
It sounds like it might be possible that the lock was created but not cleaned up when you canceled the task. 

For testing purposes, you might create a new Action to remove all locks and see if that gets things going again. The JavaScript for such an action would simply be:
```javascript
LockingSystem.unlockAll();
```

Make absolutely sure that you've got the `remove lock` task attached to the end of the workflow as well as the default error handler so that it can clean up the lock if something goes wrong.

Otherwise my only troubleshooting recommendation would be to drop a bunch of `System.debug(variable_name);` lines throughout the actions to get a better idea of where things are going off the rails.

Good luck!

PS: there's some good detail on the locking system [here](https://vra4u.com/2019/04/29/vrolockingsystem/), btw.

**Comment by sjm-tech** [comment]
Thanks John, So that was it, the lock wasn't cleaned up.  After unlockALL it started working. Have made sure that the remove lock and the default error handler are in place. 

Regards,
Sudheesh

**Comment by bstreet1967** [comment]
Hi John, I've used this naming WF before (thank you) with no issues. This time I am on the VMware SaaS platform. When the WF runs, it checks everything and assigns the name correctly (checked the logs) BUT the VM never actually changes the name.  Does the SaaS offering work with this code?

**Comment by vimwtf** [comment]
@bstreet1967,

 That's a great question! Unfortunately I don't have any experience with the SaaS version of vRA. I wouldn't have expected it to handle this any differently though. Have you double-checked to be sure that your workflow is returning the array-of-strings `resourceNames`?

**Comment by bstreet1967** [comment]
Here is a log snippet. Everything runs clean in the logs. 

2022-10-10 10:28:08.980 -04:00INFO************ ==> unpack results for all hosts ************
2022-10-10 10:28:08.985 -04:00INFO__item_stack:/item5/item6
2022-10-10 10:28:08.987 -04:00INFO************ ==> generate hostNameSeq & candidateVmName ************
2022-10-10 10:28:09.021 -04:00INFOProposed VM name: MYNEWNAME
2022-10-10 10:28:09.027 -04:00INFO__item_stack:/item5/item7
2022-10-10 10:28:09.028 -04:00INFO************ ==> Checking for vm names conflicts ************
2022-10-10 10:28:09.029 -04:00INFONo VM name conflicts found for MYNEWNAME
2022-10-10 10:28:09.034 -04:00INFO__item_stack:/item5/item14
2022-10-10 10:28:09.035 -04:00INFO************ ==> Checking for AD conflicts ************
2022-10-10 10:28:09.050 -04:00INFOSearched AD for: MYNEWNAME
2022-10-10 10:28:09.051 -04:00INFONo AD objects found.
2022-10-10 10:28:09.052 -04:00INFONo AD conflict found for MYNEWNAME
2022-10-10 10:28:09.057 -04:00INFO__item_stack:/item5/item13
2022-10-10 10:28:09.058 -04:00INFO************ ==> Checking for DNS conflicts ************
2022-10-10 10:28:11.489 -04:00INFONo DNS conflict for MYNEWNAME
2022-10-10 10:28:11.496 -04:00INFO__item_stack:/item5/item9
2022-10-10 10:28:11.498 -04:00INFO************ ==> Sending the name back ************
2022-10-10 10:28:11.499 -04:00INFO ***** Selecting [MYNEWNAME] as the next VM name ***** 
2022-10-10 10:28:11.504 -04:00INFO__item_stack:/item5/item10
2022-10-10 10:28:11.505 -04:00INFO************ ==> Unlocking... ************
2022-10-10 10:28:11.513 -04:00INFO__item_stack:/item5/item0
2022-10-10 10:28:11.517 -04:00INFO__item_stack:/item5
2022-10-10 10:28:11.520 -04:00INFO__item_stack:/item4
2022-10-10 10:28:11.521 -04:00INFO************ ==> apply new names ************
2022-10-10 10:28:11.522 -04:00INFOReplacing resourceName 'Cloud_Machine_1-mcm3313-213804787957' with 'MYNEWNAME'
2022-10-10 10:28:11.523 -04:00INFO************ ==> DONE ************
2022-10-10 10:28:11.525 -04:00INFO__item_stack:/item0

**Comment by jsauter42** [comment]
You saved my deployment to vRA 8. Our 7.6 deployment used a custom package from Daily Hypervisor that is not available with vRA 8.  Our custom naming is much like yours and i tried to use the built in custom naming but couldn't find a way to programmatically add "Matching Patterns" with each different build type so the incrementing numbers would not work correctly without me manually adding hundreds of new patterns.  Thankyou!!!  Yours worked perfectly..

**Comment by vimwtf** [comment]
Hi @jsauter42,

That's really great to hear!

I'm not doing a lot of vRA work these days (so unfortunately the posts on vRA probably won't resume any time soon), but I'm really glad that my efforts were able to help you out.

Thanks for letting me know!
